#Which vendors have the most trips, and what is the total revenue generated by that vendor?
from mrjob.job import MRJob
from mrjob.step import MRStep

class VendorRevenue(MRJob):

    def steps(self):
        return [
            MRStep(mapper=self.mapper, reducer=self.reducer),
            MRStep(reducer=self.max_revenue_reducer)
        ]
    
    def mapper(self, _, line):
        if not line.startswith('VendorID'):
            data = line.strip().split(',')
            VendorID = data[0]
            revenue = float(data[16])
            yield VendorID, revenue
    
    def reducer(self, key, values):
        total_revenue = sum(values)
        yield None, (total_revenue, key)
    
    def max_revenue_reducer(self, _, values):
        maximum_revenue, VendorID = max(values)
        yield VendorID, maximum_revenue


if __name__ == '__main__':
    VendorRevenue.run()